name: CI - ForgeTDD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test on Self-Hosted Runner
    runs-on: self-hosted

    steps:
      # リポジトリをチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 必要な依存関係をインストール
      - name: Install Dependencies
        run: |
          xcodebuild -version
          swift --version

      # ビルド
      - name: Build Project
        run: |
          xcodebuild \
            -project ForgeTDD.xcodeproj \
            -scheme ForgeTDD \
            -sdk macosx \
            -destination 'platform=macOS,arch=arm64' \
            build

      # 単体テスト
      - name: Run Unit Tests
        run: |
          xcodebuild \
            -project ForgeTDD.xcodeproj \
            -scheme ForgeTDD \
            -sdk macosx \
            -destination 'platform=macOS,arch=arm64' \
            test

      # 成功通知
      - name: Notify Success
        if: success()
        run: echo "✅ Build and Tests passed successfully!"
