name: CI - ForgeTDD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test on Self-Hosted Runner
    runs-on: self-hosted

    steps:
      # リポジトリをチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v3

      # SPMキャッシュの設定
      - name: Cache Swift Package Manager
        uses: actions/cache@v3
        with:
          path: |
            ~/.swiftpm
            .build
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-

      # 必要な依存関係を解決
      - name: Resolve Dependencies
        run: |
          swift package resolve

      # ビルド
      - name: Build Project
        run: |
          xcodebuild \
            -project ForgeTDD.xcodeproj \
            -scheme ForgeTDD \
            -sdk macosx \
            -destination 'platform=macOS,arch=arm64' \
            build

      # 単体テスト
      - name: Run Unit Tests
        run: |
          xcodebuild \
            -project ForgeTDD.xcodeproj \
            -scheme ForgeTDD \
            -sdk macosx \
            -destination 'platform=macOS,arch=arm64' \
            test

      # 成功通知
      - name: Notify Success
        if: success()
        run: echo "✅ Build and Tests passed successfully!"
